const errors = {
    INCORRECT_CREDENTIAL: "EB001",
    ACCOUNT_NOT_VERIFIED: "EB002",
    ERROR_OCCURED: "EB003",
    ACCOUNT_NOT_ACTIVE: "EB004",
    ACCOUNT_EXIST: "EB005",
    OTP_NOT_VALID: "EB006",
    RESTRICTED: "EB007",
    NOT_FOUND: "EB008"
}

export default errors;